#!/usr/bin/env python3
"""Render the frozen per-level diagnostic appendix from audited raw studies."""
import argparse
import hashlib
import json
from pathlib import Path
import statistics as st

from profile_reduction_kernel_levels import audit, MODES, PHASES


def label(case):
    return Path(case['input']).stem.replace('grid-', '')


def ratio(row):
    lo, hi = row['paired_ratio_bootstrap_95_interval']
    return f"{row['median_paired_ratio']:.4f} [{lo:.4f}, {hi:.4f}]"


def render(root):
    lines = ['# RK level-profile numerical appendix', '',
             'Generated by `tools/render_rk_level_profile.py`. Times are milliseconds.',
             'Each cell is a median over ten diagnostic blocks unless stated otherwise.',
             'Paired ratios are medians of within-block ratios; brackets are 95% bootstrap intervals.', '',
             '## Coarse level timelines', '',
             'The longest level is selected independently in each coarse trace. Duration/wall is',
             'the median of within-trace fractions, not a ratio of the displayed medians.',
             'Controls can have different longest levels between repetitions. Task IDs are not cores.', '',
             '| Study | Input | Workers | RK plain | Longest level IDs | Start | Duration | Level wall | Duration/wall |',
             '| --- | --- | --- | --- | --- | --- | --- | --- | --- |']
    studies = []
    for name in ('main', 'confirmation'):
        data = json.loads((root / f'rk-level-profile-{name}.json').read_text())
        audit(data); studies.append((name, data))
        for c in sorted(data['cases'], key=lambda c: (label(c), c['workers'])):
            traces = [b['rows']['rk_levels_coarse']['level_trace'] for b in c['blocks']]
            longest = [max(t['levels'], key=lambda r: r['duration_seconds']) for t in traces]
            med = lambda key: 1000 * st.median(r[key] for r in longest)
            plain = 1000 * st.median(b['rows']['rk_plain']['algorithm_seconds'] for b in c['blocks'])
            ids = ', '.join(map(str, sorted({r['level'] for r in longest})))
            wall = 1000 * st.median(t['level_wall_seconds'] for t in traces)
            fraction = st.median(r['duration_seconds'] / t['level_wall_seconds'] for r, t in zip(longest, traces))
            lines.append(f"| {name} | {label(c)} | {c['workers']} | {plain:.4f} | {ids} | {med('start_seconds'):.4f} | {med('duration_seconds'):.4f} | {wall:.4f} | {100*fraction:.2f}% |")
    lines += ['', '## Dominant-level detailed phases at eight workers', '',
              'Phase columns are separate medians and need not add to the median duration.',
              'Closure and facet-execution fractions are medians of per-trace fractions.', '',
              '| Study | Input | Level | Duration | Closure | Discovery | Incidence | Facet execution | Aggregation | Merge | Closure share | Facet share |',
              '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |']
    for name, data in studies:
        for c in sorted(data['cases'], key=label):
            if c['workers'] != 8 or not ('seed3' in label(c) or 'seed4' in label(c)):
                continue
            rows = [max(b['rows']['rk_levels_detailed']['level_trace']['levels'], key=lambda r: r['duration_seconds']) for b in c['blocks']]
            times = ' | '.join(f"{1000*st.median(r[k] for r in rows):.4f}" for k in ('duration_seconds',) + PHASES)
            shares = ' | '.join(f"{st.median(100*r[k]/r['duration_seconds'] for r in rows):.2f}%" for k in ('closure_seconds', 'facet_execution_seconds'))
            lines.append(f"| {name} | {label(c)} | {rows[0]['level']} | {times} | {shares} |")
    lines += ['', '## Instrumentation overhead', '',
              'Ratios above one mean the numerator mode is slower. These are not algorithm speedups.', '',
              '| Study | Input | Workers | Mode ratio | Paired ratio [95% interval] |',
              '| --- | --- | --- | --- | --- |']
    for name, data in studies:
        for c in sorted(data['cases'], key=lambda c: (label(c), c['workers'])):
            for key, row in c['overheads'].items():
                lines.append(f"| {name} | {label(c)} | {c['workers']} | `{key}` | {ratio(row)} |")
    lines += ['', '## Unprofiled old/new regression controls', '',
              'Six paired blocks of two repetitions per algorithm. Ratios compare the new',
              'diagnostic-capable headers to the preceding commit, with tracing disabled.', '',
              '| Study | Input | Workers | Algorithm | Candidate/baseline [95% interval] |',
              '| --- | --- | --- | --- | --- |']
    for name in ('main', 'confirmation'):
        data = json.loads((root / f'rk-level-profile-controls-{name}.json').read_text())
        for c in data['cases']:
            source = Path(data['inputs'][c['input_index']]['path']).stem
            for method, summary in c['summary'].items():
                lines.append(f"| {name} | {source} | {c['workers']} | {method} | {ratio(summary['algorithm_seconds'])} |")
    lines += ['', '## Raw evidence hashes', '']
    for suffix in ('main', 'confirmation', 'controls-main', 'controls-confirmation'):
        path = root / f'rk-level-profile-{suffix}.json'
        lines.append(f"- `{path.name}`: `{hashlib.sha256(path.read_bytes()).hexdigest()}`")
    return '\n'.join(lines) + '\n'


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--raw-dir', type=Path, default=Path(__file__).resolve().parents[2])
    p.add_argument('--check', type=Path)
    a = p.parse_args()
    content = render(a.raw_dir)
    if a.check:
        if a.check.read_text() != content:
            raise SystemExit('Level-profile appendix is stale')
        print('Level-profile appendix matches raw evidence')
    else:
        print(content, end='')


if __name__ == '__main__':
    main()
