#!/usr/bin/env python3
"""Render the synthetic scale table from benchmark CSV rows."""

from __future__ import annotations

import argparse
import csv
import math
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT.parent / "work" / "synthetic_scale_size48_portfolio.csv"
DEFAULT_TABLE_OUTPUT = ROOT / "docs" / "synthetic_scale_table.tex"
DEFAULT_PROSE_OUTPUT = ROOT / "docs" / "synthetic_scale_prose.tex"
DEFAULT_FAMILIES = ("lower-star", "plateau", "rips")
DEFAULT_STRATEGIES = ("f-max", "f-min", "saturated", "same-level-reduction")
STRATEGY_LABELS = {
    "f-max": r"\texttt{f-max}",
    "f-min": r"\texttt{f-min}",
    "saturated": r"\texttt{saturated}",
    "same-level-reduction": r"\slred",
}


@dataclass(frozen=True)
class RatioSummary:
    median: float
    q1: float
    q3: float
    samples: int


@dataclass(frozen=True)
class SyntheticScaleRow:
    family: str
    strategy: str
    cases: int
    avg_simplices: float
    critical_percent: float
    morse_us: float
    standard_over_morse: RatioSummary


def _float(row: dict[str, str], key: str) -> float:
    value = row.get(key, "")
    if value == "":
        raise ValueError(f"Missing required numeric column {key!r}.")
    return float(value)


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def _quantile(values: list[float], probability: float) -> float:
    if not values:
        raise ValueError("Cannot compute a quantile of an empty list.")
    ordered = sorted(values)
    if len(ordered) == 1:
        return ordered[0]
    position = (len(ordered) - 1) * probability
    lower = math.floor(position)
    upper = math.ceil(position)
    if lower == upper:
        return ordered[lower]
    weight = position - lower
    return ordered[lower] * (1.0 - weight) + ordered[upper] * weight


def _ratio_summary(values: Iterable[float]) -> RatioSummary:
    materialized = list(values)
    return RatioSummary(
        median=_quantile(materialized, 0.5),
        q1=_quantile(materialized, 0.25),
        q3=_quantile(materialized, 0.75),
        samples=len(materialized),
    )


def summarize_rows(
    rows: Iterable[dict[str, str]],
    *,
    families: Iterable[str] = DEFAULT_FAMILIES,
    strategies: Iterable[str] = DEFAULT_STRATEGIES,
) -> list[SyntheticScaleRow]:
    family_order = tuple(families)
    strategy_order = tuple(strategies)
    family_rank = {family: index for index, family in enumerate(family_order)}
    strategy_rank = {strategy: index for index, strategy in enumerate(strategy_order)}
    grouped: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        family = row.get("family", "")
        strategy = row.get("sequence_algorithm", "")
        if family in family_rank and strategy in strategy_rank:
            grouped[(family, strategy)].append(row)

    summaries: list[SyntheticScaleRow] = []
    for family in family_order:
        for strategy in strategy_order:
            group = grouped.get((family, strategy), [])
            if not group:
                continue
            cases = len(group)
            avg_simplices = sum(_float(row, "num_simplices") for row in group) / cases
            avg_criticals = (
                sum(_float(row, "num_critical_simplices") for row in group) / cases
            )
            summaries.append(
                SyntheticScaleRow(
                    family=family,
                    strategy=strategy,
                    cases=cases,
                    avg_simplices=avg_simplices,
                    critical_percent=(
                        100.0 * avg_criticals / avg_simplices
                        if avg_simplices
                        else 0.0
                    ),
                    morse_us=(
                        1.0e6 * sum(_float(row, "morse_seconds") for row in group) / cases
                    ),
                    standard_over_morse=_ratio_summary(
                        _float(row, "speedup") for row in group
                    ),
                )
            )
    return summaries


def _format_number(value: float, digits: int = 1) -> str:
    text = f"{value:,.{digits}f}"
    return text


def _format_ratio(summary: RatioSummary) -> str:
    if summary.samples <= 1:
        return f"{summary.median:.2f}"
    return (
        r"\ratioiqr{"
        f"{summary.median:.2f}"
        r"}{"
        f"{summary.q1:.2f}"
        r"}{"
        f"{summary.q3:.2f}"
        r"}"
    )


def render_latex_table(rows: list[SyntheticScaleRow]) -> str:
    lines = [
        "% Generated by morseframes/tools/render_synthetic_scale_table.py.",
        "% Re-run that script instead of editing this table by hand.",
        r"\providecommand{\ratioiqr}[3]{\shortstack[c]{#1\\[-0.25ex]{\tiny #2--#3}}}",
        r"\begin{table}[ht]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{tabular}{llrrrrc}",
        r"\toprule",
        r"Family & Strategy & Cases & Avg. simplices & Critical \% & Morse (\us) & Std/Morse \\",
        r"\midrule",
    ]
    previous_family: str | None = None
    for row in rows:
        if previous_family is not None and row.family != previous_family:
            lines.append(r"\midrule")
        previous_family = row.family
        lines.append(
            f"{row.family} & "
            f"{STRATEGY_LABELS.get(row.strategy, row.strategy)} & "
            f"{row.cases} & "
            f"{_format_number(row.avg_simplices)} & "
            f"{row.critical_percent:.1f} & "
            f"{_format_number(row.morse_us)} & "
            f"{_format_ratio(row.standard_over_morse)} \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            (
                r"\caption{Representative synthetic scale results at size $48$ for the "
                r"core same-level strategy family.  The \texttt{Std/Morse} ratio "
                r"shows the median with $Q_1$--$Q_3$ underneath over the listed "
                r"cases, so values above $1$ indicate that the Morse pipeline is "
                r"faster than ordinary full-complex persistence for that row.  "
                r"These controlled examples are intended as implementation "
                r"diagnostics; denser Rips cases are the clearest stress test "
                r"among the rows shown here.}"
            ),
            r"\label{tab:synthetic-scale}",
            r"\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


def render_prose(rows: list[SyntheticScaleRow]) -> str:
    by_family: dict[str, list[SyntheticScaleRow]] = defaultdict(list)
    for row in rows:
        by_family[row.family].append(row)
    winners = {
        family: min(group, key=lambda row: row.morse_us)
        for family, group in by_family.items()
    }
    winner_fragments = [
        f"{family}: {STRATEGY_LABELS.get(row.strategy, row.strategy)}"
        for family, row in winners.items()
    ]
    rips_group = by_family.get("rips", [])
    rips_winners = [
        row for row in rips_group
        if row.standard_over_morse.median > 1.0
    ]
    lines = [
        "% Generated by morseframes/tools/render_synthetic_scale_table.py.",
        "% Re-run that script instead of editing this paragraph by hand.",
        "These experiments show why \\texttt{f-max} and \\texttt{f-min} must "
        "remain in the measured portfolio: the fastest core strategy in this "
        f"representative run is {', '.join(winner_fragments)}.",
    ]
    if rips_winners:
        lines.append(
            "On denser Rips complexes, several Morse strategies begin to beat standard "
            "persistence, which is the regime where standard reduction becomes expensive."
        )
    lines.append("")
    return "\n".join(lines)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render the synthetic scale LaTeX table from benchmark CSV rows."
    )
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--table-output", type=Path, default=DEFAULT_TABLE_OUTPUT)
    parser.add_argument("--prose-output", type=Path, default=DEFAULT_PROSE_OUTPUT)
    parser.add_argument("--families", nargs="+", default=list(DEFAULT_FAMILIES))
    parser.add_argument("--strategies", nargs="+", default=list(DEFAULT_STRATEGIES))
    parser.add_argument("--stdout", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    rows = summarize_rows(
        read_rows(args.input),
        families=args.families,
        strategies=args.strategies,
    )
    if not rows:
        raise ValueError("No synthetic scale rows matched the requested filters.")
    table = render_latex_table(rows)
    prose = render_prose(rows)
    args.table_output.parent.mkdir(parents=True, exist_ok=True)
    args.prose_output.parent.mkdir(parents=True, exist_ok=True)
    args.table_output.write_text(table)
    args.prose_output.write_text(prose)
    if args.stdout:
        sys.stdout.write(table)
        sys.stdout.write("\n")
        sys.stdout.write(prose)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
