#!/usr/bin/env python3
"""Render every frozen parallel-closure comparison, keeping process pairs separate."""
import argparse
import hashlib
import json
from pathlib import Path
import statistics

import benchmark_rk_parallel_closure as study
from render_rk_binary_isolation import ratio


def load(paths):
    data = [json.loads(p.read_text()) for p in paths]
    assert len(data) == 2 and not data[0]['settings']['reverse'] and data[1]['settings']['reverse']
    assert all(len(d['cases']) == len(d['settings']['inputs'])*4 for d in data)
    assert data[0]['source_sha256'] == data[1]['source_sha256']
    assert data[0]['settings']['inputs'] == data[1]['settings']['inputs'][::-1]
    assert data[0]['settings']['workers'] == data[1]['settings']['workers'][::-1]
    assert data[0]['settings'].get('baseline_closure_serial', False) == data[1]['settings'].get('baseline_closure_serial', False)
    for d in data:
        for case in d['cases']:
            # Includes independent recomputation, source hashes audited separately.
            study.validate_case(case, d)
    return data


def cases_by_key(data):
    grouped = {}
    for session, d in zip(('Main', 'Confirmation'), data):
        for c in d['cases']:
            grouped.setdefault((Path(c['input']).name,c['workers']),[]).append((session,c))
    assert len(grouped)==len(data[0]['settings']['inputs'])*2 and all(len(rows)==4 for rows in grouped.values())
    return grouped


def estimate(rows, comparison, method='reduction_kernel', phase='algorithm_seconds'):
    values=[c['summary'][comparison][method][phase]['median_paired_ratio'] for _,c in rows]
    return f'{statistics.median(values):.4f} [{min(values):.4f}, {max(values):.4f}]'


def render(paths, report='rk_parallel_closure_benchmark.md', protocol='rk_parallel_closure_protocol.md'):
    data=load(paths); grouped=cases_by_key(data)
    count=sum(len(d['cases']) for d in data)*27
    lines=['# Parallel RK closure: complete numerical results','',
           f'Generated by `tools/render_rk_parallel_closure.py`. All {count:,} phase summaries',
           'are independently recomputed from raw repetitions before rendering.',
           f'See the [experiment report]({report}) and',
           f'[frozen protocol]({protocol}).','',
           'Ratios above one mean slower. Loading/native construction are separate',
           'single observations per process; they are not part of gradient timing.',
           'Both candidate modes share one process and executable. F-Max stays sequential.','',
           '## Across independent process pairs','',
           'Each entry is the median of four paired-block estimates, followed by their',
           '**observed minimum and maximum**, not a confidence interval. Inputs are',
           'selected synthetic controls, not a representative corpus.','',
           '| Input | Workers | RK on / off | RK on / baseline | RK off / baseline |',
           '| --- | ---: | --- | --- | --- |']
    for (name,w),rows in grouped.items():
        lines.append(f'| {name} | {w} | '+ ' | '.join(estimate(rows,k) for k in
            ('candidate_on/candidate_off','candidate_on/baseline','candidate_off/baseline'))+' |')
    if data[0]['settings'].get('baseline_closure_serial', False):
        lines += ['', 'Baseline uses `run_closure_serial`: its opt-in closure feature is disabled.',
                  'Candidate-on uses its recorded header default size threshold; candidate-off',
                  'disables closure parallelism. The baseline is not the previous broad-on mode.']
    lines += ['', '## Critical simplices and identity', '',
              '| Input | Simplices | F-Max critical counts | PLS critical counts | RK critical counts |',
              '| --- | ---: | --- | --- | --- |']
    for (name,w),rows in grouped.items():
        if w!=1: continue
        identity=rows[0][1]['metadata']['baseline']['identity']
        counts=[' / '.join(map(str,identity['algorithms'][m]['critical_counts'])) for m in study.common.ALGORITHMS]
        lines.append(f"| {name} | {identity['simplices']:,} | "+' | '.join(counts)+' |')
    for session,path,d in zip(('Main','Confirmation'),paths,data):
        lines += ['',f'## {session} provenance','',f'Raw file: `{path.name}`.','',
                  f"SHA-256: `{hashlib.sha256(path.read_bytes()).hexdigest()}`.",'',
                  f"Frozen runner: `{d['source_revision']}`.",'',
                  f"Timing window (UTC): {d['started_utc']} to {d['finished_utc']}.",'',
                  '| Build | Header revision | Binary SHA-256 |','| --- | --- | --- |']
        for v,b in d['builds'].items():
            lines.append(f"| {v} | `{b['revision']}` | `{b['binary_sha256']}` |")
    lines += ['', '## Individual process-pair comparisons', '',
              'Here brackets are **95% paired-block bootstrap intervals** (2,000 resamples,',
              'seed 0), conditional on one process pair. They are not cross-process intervals.',
              'Total medians are milliseconds. Builder, kernel and total ratios use their own',
              'paired blocks; do not derive them by dividing separately displayed medians.']
    names={'f_max':'F-Max','process_lower_stars':'PLS','reduction_kernel':'RK'}
    for (name,w),rows in grouped.items():
        for session,c in rows:
            lines += ['', f"### {session} pair {c['replicate']}: {name}, {w} workers", '',
                      f"Ordered reference SHA-256: `{c['reference_sha256']}`.", '',
                      '| Process | Loading ms | Construction ms |','| --- | ---: | ---: |']
            for v,m in c['metadata'].items():
                lines.append(f"| {v} | {1000*m['loading_seconds']:.3f} | {1000*m['construction_seconds']:.3f} |")
            lines += ['', '| Comparison | Method | Denom. total ms | Numer. total ms | Builder ratio [CI] | Kernel ratio [CI] | Total ratio [CI] |',
                      '| --- | --- | ---: | ---: | --- | --- | --- |']
            for comparison,methods in c['summary'].items():
                for m,phases in methods.items():
                    med=phases['algorithm_seconds']['median_seconds']
                    lines.append(f"| {comparison} | {names[m]} | {1000*med['baseline']:.3f} | {1000*med['candidate']:.3f} | "+
                                 ' | '.join(ratio(phases[p]) for p in study.common.PHASES)+' |')
    return '\n'.join(lines)+'\n'


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--inputs',type=Path,nargs=2,required=True)
    p.add_argument('--output',type=Path,required=True)
    p.add_argument('--check',action='store_true')
    p.add_argument('--report',default='rk_parallel_closure_benchmark.md')
    p.add_argument('--protocol',default='rk_parallel_closure_protocol.md')
    args=p.parse_args(); output=render(args.inputs,args.report,args.protocol)
    if args.check: assert args.output.read_text()==output, 'Generated results are stale'
    else: args.output.write_text(output)
    print('All independently recomputed phase summaries and rendered tables agree')


if __name__=='__main__': main()
