#!/usr/bin/env python3
"""Independently recompute every timing summary and render the isolation appendix.

Deliberately does not import the runners or their statistics implementation.
Provenance/gradient audits are separate commands documented in the report.
"""
import argparse
import hashlib
import json
import math
from pathlib import Path
import random

METHODS = ('f_max', 'process_lower_stars', 'reduction_kernel')
PHASES = ('builder_seconds', 'kernel_seconds', 'algorithm_seconds')
PAIRS = ('candidate_ordinary/baseline_ordinary', 'candidate_full/baseline_full',
         'candidate_full/candidate_ordinary', 'baseline_full/baseline_ordinary')
NAMES = dict(f_max='F-Max', process_lower_stars='PLS', reduction_kernel='RK')


def quantile(values, fraction):
    ordered = sorted(values)
    x = fraction * (len(ordered) - 1)
    lo, hi = math.floor(x), math.ceil(x)
    return ordered[lo] + (ordered[hi] - ordered[lo]) * (x - lo)


def recompute(blocks, numerator, denominator, method, phase):
    groups = {v: [[r[method][phase] for r in b['runs'][v]] for b in blocks]
              for v in (denominator, numerator)}
    ratios = [quantile(n, .5) / quantile(d, .5)
              for n, d in zip(groups[numerator], groups[denominator])]
    rng = random.Random(0)
    n = len(ratios)
    bootstrap = sorted(quantile([ratios[int(rng.random() * n)] for _ in range(n)], .5)
                       for _ in range(2000))
    flat = {label: sum(groups[v], []) for label, v in
            [('baseline', denominator), ('candidate', numerator)]}
    return dict(median_seconds={k: quantile(v, .5) for k, v in flat.items()},
                iqr_seconds={k: [quantile(v, .25), quantile(v, .75)] for k, v in flat.items()},
                median_paired_ratio=quantile(ratios, .5),
                paired_ratio_iqr=[quantile(ratios, .25), quantile(ratios, .75)],
                paired_ratio_bootstrap_95_interval=[bootstrap[49], bootstrap[1949]],
                faster_blocks=sum(r < 1 for r in ratios), blocks=n)


def check_equal(actual, expected):
    if isinstance(expected, dict):
        assert actual.keys() == expected.keys()
        for k in expected:
            check_equal(actual[k], expected[k])
    elif isinstance(expected, list):
        assert len(actual) == len(expected)
        for a, e in zip(actual, expected):
            check_equal(a, e)
    else:
        assert math.isclose(actual, expected, rel_tol=1e-12, abs_tol=1e-15), (actual, expected)


def independently_check(data):
    count = 0
    cases = data.get('cases', data.get('pairs'))
    for case in cases:
        comparisons = [(k, *k.split('/')) for k in PAIRS] if 'cases' in data else [(None, 'b', 'a')]
        for key, numerator, denominator in comparisons:
            stored = case['summary'][key] if key else case['summary']
            for method in METHODS:
                for phase in PHASES:
                    check_equal(stored[method][phase], recompute(case['blocks'], numerator, denominator, method, phase))
                    count += 1
    return count


def ratio(row):
    low, high = row['paired_ratio_bootstrap_95_interval']
    return f"{row['median_paired_ratio']:.4f} [{low:.4f}, {high:.4f}]"


def render(paths):
    loaded = [(p, json.loads(p.read_text())) for p in paths]
    assert len(loaded) == 3
    assert [d['schema'] for _, d in loaded] == ['rk-binary-isolation-v1'] * 2 + ['rk-same-binary-v1']
    count = sum(independently_check(d) for _, d in loaded)
    lines = ['# RK binary-isolation numerical appendix', '',
             'Generated by `tools/render_rk_binary_isolation.py` after independent recomputation',
             f'of all **{count} phase summaries** from individual raw repetitions.',
             'See the [report](rk_binary_isolation_benchmark.md) for conclusions and limitations.', '',
             'Ratios are numerator/denominator; above one means slower. Brackets are 95%',
             'paired-block bootstrap intervals (2,000 resamples, seed 0). They describe blocks',
             'within one process set, not between-process or cross-machine uncertainty.',
             'Total gradient medians are milliseconds. Builder and kernel intervals are retained',
             'alongside total intervals; total includes builder plus kernel. Separate medians need',
             'not add exactly. Loading/construction rows are single untimed-setup observations',
             'per process, reported separately and not treated as a construction benchmark.', '',
             '## Frozen inputs and references', '',
             '| Input | Simplices | F-Max critical counts | PLS critical counts | RK critical counts |',
             '| --- | ---: | --- | --- | --- |']
    for c in loaded[0][1]['cases'][::2]:
        identity = c['metadata']['baseline_ordinary']['identity']
        counts = [' / '.join(map(str, identity['algorithms'][m]['critical_counts'])) for m in METHODS]
        lines.append(f"| {Path(c['input']).name} | {identity['simplices']:,} | " + ' | '.join(counts) + ' |')
    for study, (path, data) in zip(('Main', 'Reversed confirmation', 'Identical-binary A/A'), loaded):
        lines += ['', f'## {study}', '', f"Raw file: `{path.name}`.", '',
                  f"SHA-256: `{hashlib.sha256(path.read_bytes()).hexdigest()}`.", '',
                  f"Runner commit: `{data['source_revision']}`.", '',
                  f"Timing window (UTC): {data['started_utc']} to {data['finished_utc']}."]
        if 'cases' in data:
            lines += ['', '| Executable | Bytes | Trace symbols | Binary SHA-256 |', '| --- | ---: | ---: | --- |']
            for name, build in data['builds'].items():
                lines.append(f"| {name} | {build['bytes']} | {build['trace_symbol_count']} | `{build['binary_sha256']}` |")
        for c in data.get('cases', data.get('pairs')):
            label = Path(c.get('input', data.get('input', ''))).name
            suffix = f", process pair {c['pair']}" if 'pair' in c else ''
            lines += ['', f"### {study}: {label}, {c['workers']} workers{suffix}", '',
                      f"Ordered reference SHA-256: `{c['reference_sha256']}`.", '',
                      '| Process | Load ms | Native construction ms |', '| --- | ---: | ---: |']
            for v, meta in c['metadata'].items():
                lines.append(f"| {v} | {1000*meta['loading_seconds']:.3f} | {1000*meta['construction_seconds']:.3f} |")
            lines += ['', '| Comparison | Method | Denom. total ms | Numer. total ms | Builder ratio [CI] | Kernel ratio [CI] | Total ratio [CI] |',
                      '| --- | --- | ---: | ---: | --- | --- | --- |']
            comparisons = c['summary'] if 'cases' in data else {'b/a (same executable)': c['summary']}
            for key, methods in comparisons.items():
                for m, phases in methods.items():
                    med = phases['algorithm_seconds']['median_seconds']
                    lines.append(f"| {key} | {NAMES[m]} | {1000*med['baseline']:.3f} | {1000*med['candidate']:.3f} | " +
                                 ' | '.join(ratio(phases[p]) for p in PHASES) + ' |')
    return '\n'.join(lines) + '\n'


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--inputs', type=Path, nargs=3, required=True)
    p.add_argument('--output', type=Path, required=True)
    p.add_argument('--check', action='store_true')
    args = p.parse_args()
    result = render(args.inputs)
    if args.check:
        assert args.output.read_text() == result, 'Generated appendix is stale'
    else:
        args.output.write_text(result)
    print('Independent numerical QA and appendix', 'check' if args.check else 'render', 'passed')


if __name__ == '__main__':
    main()
